tape = []; cur = 0
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
tape[cur] ||= 0; tape[cur] += 1
puts (tape[cur] || 0).chr
